services:
  - type: web
    name: iclr-backend
    env: node
    plan: free
    rootDir: iclr-node-server-app
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_CONNECTION_STRING
        sync: false
      - key: FRONTEND_URL
        value: https://your-frontend-name.netlify.app 